### ISSUE TITLE
ebay-menu with icon label flips both the icon and chevron when opened

### ISSUE THREAD

**Issue by scttdavs** [eBay/ebayui-core#355]
# Bug Report

## Description
Same as the title of this issue.

```css
.button.expand-btn[aria-expanded=true] .expand-btn__icon {
    transform: rotate(180deg);
}
```
this css applies to both the icon label and the chevron. Some icons appear to move when they are flipped due to this. It should only flip the chevron, if it exists.

## Screenshots
![icon-jump](https://user-images.githubusercontent.com/3631216/44220286-2a0ece80-a14c-11e8-9f06-526b4bbdce7a.gif)
